---

- name: check go version
  command: go version
  register: result
  changed_when: no
  ignore_errors: true
  become: yes
  become_user: vagrant

- name:
  shell: >
    getent passwd vagrant | cut -d: -f6
  changed_when: false
  register: user_home

- debug:
    msg: Go Fact {{ user_home.stdout }}

- set_fact:
    go_path: "{{ lookup('env', 'GOPATH') | default(user_home.stdout+'/go', true) }}"
  when: not result is failed
  become: yes
  become_user: vagrant

- debug:
    msg: Go Fact {{ go_path }}

- name: Get Kind
  shell: go get sigs.k8s.io/kind@v0.4.0
  environment:
    GOPATH: "{{ go_path }}"
    GO111MODULE: "on"
  become: yes
  become_user: vagrant
