---

- name: check go version
  command: go version
  register: result
  changed_when: no
  ignore_errors: true
  become: yes
  become_user: "{{ install_user }}"

- name: Register users home directory path
  shell: >
    getent passwd {{ install_user }} | cut -d: -f6
  changed_when: false
  register: user_home

- debug:
    msg: Go Fact {{ user_home.stdout }}

- set_fact:
    go_path: "{{ lookup('env', 'GOPATH') | default(user_home.stdout+'/go', true) }}"
  when: not result is failed
  become: yes
  become_user: "{{ install_user }}"

- debug:
    msg: Go Fact {{ go_path }}

- name: Get Kind
  shell: go get sigs.k8s.io/kind@v0.4.0
  environment:
    GOPATH: "{{ go_path }}"
    GO111MODULE: "on"
  become: yes
  become_user: "{{ install_user }}"

- name: Ensures conf dir exists
  file: path="{{ project_config_dir }}" state=directory

- name: Copy config file over
  copy:
    src: kind-config.yaml
    dest: "{{ project_config_dir }}/kind-config.yaml"
    owner: "{{ install_user }}"
    group: "{{ install_user }}"
    mode: '0644'

- name: Run Kind
  shell: >
    {{ go_path }}/bin/kind create cluster --config {{ project_config_dir }}/kind-config.yaml
  become: yes
  become_user: "{{ install_user }}"

- debug:
    msg: run export KUBECONFIG="$(kind get kubeconfig-path)" before running kubectl
